from core.configs import SMTP_HOST, SMTP_PORT, SMTP_USE_TLS, SMTP_USE_SSL, SMTP_USERNAME, SMTP_PASSWORD, SMTP_SEND_FROM
# Flask-Mail SMTP configuration for production
MAIL_SERVER = SMTP_HOST
MAIL_PORT = SMTP_PORT
MAIL_USE_TLS = SMTP_USE_TLS
MAIL_USE_SSL = SMTP_USE_SSL
MAIL_USERNAME = SMTP_USERNAME
MAIL_PASSWORD = SMTP_PASSWORD
MAIL_DEFAULT_SENDER = SMTP_SEND_FROM
